### ISSUE TITLE
twitterizer does not work with the latest version of JSON

### ISSUE THREAD

**Issue by vishnu4** [Twitterizer/Twitterizer#19]
same issue as noted here: http://forums.twitterizer.net/viewtopic.php?f=9&t=1096 , but placed in github for posterity.  The actual exception i am getting is:

Unexpected token when deserializing object: StartObject. Path '[1]', line 1, position 5641.

Type = Newtonsoft.Json.JsonSerializationException

Source = Newtonsoft.Json

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IWrappedCollection wrappedList, JsonReader reader, String reference, JsonArrayContract contract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonProperty containerProperty, Object existingValue, String reference)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Twitterizer.Core.SerializationHelper`1.Deserialize(Byte[] webResponseData, DeserializationHandler deserializationHandler)
   at Twitterizer.Core.TwitterCommand`1.ExecuteCommand()
   at Twitterizer.TwitterTimeline.HomeTimeline(OAuthTokens tokens, TimelineOptions options)

**Comment by atisak** [comment]
same issue

**Comment by rodrigopalhares** [comment]
There are more places that occur the problem that https://github.com/phawxby fixed.

https://github.com/rodrigopalhares/Twitterizer/commit/fc429ce1b81fd508256f6c1578af2bb23876d14c

**Comment by alexander-myltsev** [comment]
Hm. rodrigopalhares, you have done great job! But 27 tests are failed?!

**Comment by rodrigopalhares** [comment]
Thx halexander-myltsev. I have had problems to setup the test environment. So, i don't know if this tests were working before my changes. Sorry...

**Comment by alexander-myltsev** [comment]
What is going on with library development? Any chance that pull requests will be added to the library and nuget package will be updated?

**Comment by rodrigopalhares** [comment]
Unfortunately, I think it was abandoned. =(

**Comment by DigitallyBorn** [comment]
It's not abandoned. I'm performing merges when they are made against the develop branch. Once people have provided me feedback about the stability of the develop branch I'll merge to master and push an update to nuget.

**Comment by rodrigopalhares** [comment]
Good news! Thx...
